/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kiruthika.pojoavro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Swipe extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7057491205813295845L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Swipe\",\"namespace\":\"com.kiruthika.pojoavro.model\",\"fields\":[{\"name\":\"dept\",\"type\":[\"null\",\"string\"]},{\"name\":\"empNo\",\"type\":[\"null\",\"string\"]},{\"name\":\"eventId\",\"type\":{\"type\":\"int\",\"java-class\":\"java.lang.Integer\"}},{\"name\":\"swipeTime\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Swipe> ENCODER =
      new BinaryMessageEncoder<Swipe>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Swipe> DECODER =
      new BinaryMessageDecoder<Swipe>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Swipe> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Swipe> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Swipe> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Swipe>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Swipe to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Swipe from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Swipe instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Swipe fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence dept;
   private java.lang.CharSequence empNo;
   private int eventId;
   private java.lang.CharSequence swipeTime;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Swipe() {}

  /**
   * All-args constructor.
   * @param dept The new value for dept
   * @param empNo The new value for empNo
   * @param eventId The new value for eventId
   * @param swipeTime The new value for swipeTime
   */
  public Swipe(java.lang.CharSequence dept, java.lang.CharSequence empNo, java.lang.Integer eventId, java.lang.CharSequence swipeTime) {
    this.dept = dept;
    this.empNo = empNo;
    this.eventId = eventId;
    this.swipeTime = swipeTime;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return dept;
    case 1: return empNo;
    case 2: return eventId;
    case 3: return swipeTime;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: dept = (java.lang.CharSequence)value$; break;
    case 1: empNo = (java.lang.CharSequence)value$; break;
    case 2: eventId = (java.lang.Integer)value$; break;
    case 3: swipeTime = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'dept' field.
   * @return The value of the 'dept' field.
   */
  public java.lang.CharSequence getDept() {
    return dept;
  }


  /**
   * Sets the value of the 'dept' field.
   * @param value the value to set.
   */
  public void setDept(java.lang.CharSequence value) {
    this.dept = value;
  }

  /**
   * Gets the value of the 'empNo' field.
   * @return The value of the 'empNo' field.
   */
  public java.lang.CharSequence getEmpNo() {
    return empNo;
  }


  /**
   * Sets the value of the 'empNo' field.
   * @param value the value to set.
   */
  public void setEmpNo(java.lang.CharSequence value) {
    this.empNo = value;
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public int getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(int value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'swipeTime' field.
   * @return The value of the 'swipeTime' field.
   */
  public java.lang.CharSequence getSwipeTime() {
    return swipeTime;
  }


  /**
   * Sets the value of the 'swipeTime' field.
   * @param value the value to set.
   */
  public void setSwipeTime(java.lang.CharSequence value) {
    this.swipeTime = value;
  }

  /**
   * Creates a new Swipe RecordBuilder.
   * @return A new Swipe RecordBuilder
   */
  public static com.kiruthika.pojoavro.model.Swipe.Builder newBuilder() {
    return new com.kiruthika.pojoavro.model.Swipe.Builder();
  }

  /**
   * Creates a new Swipe RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Swipe RecordBuilder
   */
  public static com.kiruthika.pojoavro.model.Swipe.Builder newBuilder(com.kiruthika.pojoavro.model.Swipe.Builder other) {
    if (other == null) {
      return new com.kiruthika.pojoavro.model.Swipe.Builder();
    } else {
      return new com.kiruthika.pojoavro.model.Swipe.Builder(other);
    }
  }

  /**
   * Creates a new Swipe RecordBuilder by copying an existing Swipe instance.
   * @param other The existing instance to copy.
   * @return A new Swipe RecordBuilder
   */
  public static com.kiruthika.pojoavro.model.Swipe.Builder newBuilder(com.kiruthika.pojoavro.model.Swipe other) {
    if (other == null) {
      return new com.kiruthika.pojoavro.model.Swipe.Builder();
    } else {
      return new com.kiruthika.pojoavro.model.Swipe.Builder(other);
    }
  }

  /**
   * RecordBuilder for Swipe instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Swipe>
    implements org.apache.avro.data.RecordBuilder<Swipe> {

    private java.lang.CharSequence dept;
    private java.lang.CharSequence empNo;
    private int eventId;
    private java.lang.CharSequence swipeTime;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kiruthika.pojoavro.model.Swipe.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.dept)) {
        this.dept = data().deepCopy(fields()[0].schema(), other.dept);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.empNo)) {
        this.empNo = data().deepCopy(fields()[1].schema(), other.empNo);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.eventId)) {
        this.eventId = data().deepCopy(fields()[2].schema(), other.eventId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.swipeTime)) {
        this.swipeTime = data().deepCopy(fields()[3].schema(), other.swipeTime);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Swipe instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kiruthika.pojoavro.model.Swipe other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.dept)) {
        this.dept = data().deepCopy(fields()[0].schema(), other.dept);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.empNo)) {
        this.empNo = data().deepCopy(fields()[1].schema(), other.empNo);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.eventId)) {
        this.eventId = data().deepCopy(fields()[2].schema(), other.eventId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.swipeTime)) {
        this.swipeTime = data().deepCopy(fields()[3].schema(), other.swipeTime);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'dept' field.
      * @return The value.
      */
    public java.lang.CharSequence getDept() {
      return dept;
    }


    /**
      * Sets the value of the 'dept' field.
      * @param value The value of 'dept'.
      * @return This builder.
      */
    public com.kiruthika.pojoavro.model.Swipe.Builder setDept(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.dept = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'dept' field has been set.
      * @return True if the 'dept' field has been set, false otherwise.
      */
    public boolean hasDept() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'dept' field.
      * @return This builder.
      */
    public com.kiruthika.pojoavro.model.Swipe.Builder clearDept() {
      dept = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'empNo' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmpNo() {
      return empNo;
    }


    /**
      * Sets the value of the 'empNo' field.
      * @param value The value of 'empNo'.
      * @return This builder.
      */
    public com.kiruthika.pojoavro.model.Swipe.Builder setEmpNo(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.empNo = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'empNo' field has been set.
      * @return True if the 'empNo' field has been set, false otherwise.
      */
    public boolean hasEmpNo() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'empNo' field.
      * @return This builder.
      */
    public com.kiruthika.pojoavro.model.Swipe.Builder clearEmpNo() {
      empNo = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public int getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public com.kiruthika.pojoavro.model.Swipe.Builder setEventId(int value) {
      validate(fields()[2], value);
      this.eventId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public com.kiruthika.pojoavro.model.Swipe.Builder clearEventId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'swipeTime' field.
      * @return The value.
      */
    public java.lang.CharSequence getSwipeTime() {
      return swipeTime;
    }


    /**
      * Sets the value of the 'swipeTime' field.
      * @param value The value of 'swipeTime'.
      * @return This builder.
      */
    public com.kiruthika.pojoavro.model.Swipe.Builder setSwipeTime(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.swipeTime = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'swipeTime' field has been set.
      * @return True if the 'swipeTime' field has been set, false otherwise.
      */
    public boolean hasSwipeTime() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'swipeTime' field.
      * @return This builder.
      */
    public com.kiruthika.pojoavro.model.Swipe.Builder clearSwipeTime() {
      swipeTime = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Swipe build() {
      try {
        Swipe record = new Swipe();
        record.dept = fieldSetFlags()[0] ? this.dept : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.empNo = fieldSetFlags()[1] ? this.empNo : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.eventId = fieldSetFlags()[2] ? this.eventId : (java.lang.Integer) defaultValue(fields()[2]);
        record.swipeTime = fieldSetFlags()[3] ? this.swipeTime : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Swipe>
    WRITER$ = (org.apache.avro.io.DatumWriter<Swipe>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Swipe>
    READER$ = (org.apache.avro.io.DatumReader<Swipe>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.dept == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.dept);
    }

    if (this.empNo == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.empNo);
    }

    out.writeInt(this.eventId);

    if (this.swipeTime == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.swipeTime);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.dept = null;
      } else {
        this.dept = in.readString(this.dept instanceof Utf8 ? (Utf8)this.dept : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.empNo = null;
      } else {
        this.empNo = in.readString(this.empNo instanceof Utf8 ? (Utf8)this.empNo : null);
      }

      this.eventId = in.readInt();

      if (in.readIndex() != 1) {
        in.readNull();
        this.swipeTime = null;
      } else {
        this.swipeTime = in.readString(this.swipeTime instanceof Utf8 ? (Utf8)this.swipeTime : null);
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.dept = null;
          } else {
            this.dept = in.readString(this.dept instanceof Utf8 ? (Utf8)this.dept : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.empNo = null;
          } else {
            this.empNo = in.readString(this.empNo instanceof Utf8 ? (Utf8)this.empNo : null);
          }
          break;

        case 2:
          this.eventId = in.readInt();
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.swipeTime = null;
          } else {
            this.swipeTime = in.readString(this.swipeTime instanceof Utf8 ? (Utf8)this.swipeTime : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










